name: PocketPerms
version: 1.0+dev
main: lokiPM\PocketPerms\Main
api: 5.0.0
src-namespace-prefix: lokiPM\PocketPerms

commands:
  ppgroup:
    description: Manage Permission Groups
    permission: pocketperms.*
    permission-message: You do not have permission to execute this command.
    default: op
